// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARPeawZrcgGNHqPfR0amdGEQvEnYGR4pU',
    appId: '1:1044596043012:web:7648403b2f1c0eb2653451',
    messagingSenderId: '1044596043012',
    projectId: 'skill-trainer-app',
    authDomain: 'skill-trainer-app.firebaseapp.com',
    storageBucket: 'skill-trainer-app.firebasestorage.app',
    measurementId: 'G-NNGH8X4TMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoT5Pt2EanmMUzQLMgESKNNUJJvFUAiTs',
    appId: '1:1044596043012:android:68d2423e217b8f92653451',
    messagingSenderId: '1044596043012',
    projectId: 'skill-trainer-app',
    storageBucket: 'skill-trainer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByRLp4LWVh4C-BsHJjAcCJPS3wXatpLeI',
    appId: '1:1044596043012:ios:3b97afa2742181a4653451',
    messagingSenderId: '1044596043012',
    projectId: 'skill-trainer-app',
    storageBucket: 'skill-trainer-app.firebasestorage.app',
    iosBundleId: 'com.hentran.myFirstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByRLp4LWVh4C-BsHJjAcCJPS3wXatpLeI',
    appId: '1:1044596043012:ios:3b97afa2742181a4653451',
    messagingSenderId: '1044596043012',
    projectId: 'skill-trainer-app',
    storageBucket: 'skill-trainer-app.firebasestorage.app',
    iosBundleId: 'com.hentran.myFirstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARPeawZrcgGNHqPfR0amdGEQvEnYGR4pU',
    appId: '1:1044596043012:web:865da8147a03a9ed653451',
    messagingSenderId: '1044596043012',
    projectId: 'skill-trainer-app',
    authDomain: 'skill-trainer-app.firebaseapp.com',
    storageBucket: 'skill-trainer-app.firebasestorage.app',
    measurementId: 'G-QBBRTP0T0J',
  );
}
