import 'dart:io';

void main() {
  final openaiApiKey = Platform.environment['OPENAI_API_KEY'] ?? '';

  final configContent = '''
// This file is automatically generated during build
// DO NOT EDIT MANUALLY

class Config {
  static const String openaiApiKey = '$openaiApiKey';
}
''';

  final configFile = File('lib/config.dart');
  configFile.writeAsStringSync(configContent);
  print('Generated config.dart');
}
